#!/bin/bash

# Key event listener
sxhkd &

bspc monitor -d I

bspc config border_width 1
bspc config window_gap 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

#bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc config focused_border_color "#676D3D"
bspc config normal_border_color "#737470"
bspc config presel_feedback_color "#c0b18b"

# Updating the screen resolution and set the wallpaper
# TODO check if possible to use alias here (for calling update_screen alias)
xrandr --output VGA-1 --auto
sh ~/.fehbg

# Start yabar
yabar &

# Open a new xterm
xterm &
