#!/bin/bash
#
# Inspired by windelicato's dotfiles
# With this script a config file for a specific key (program name) is opened

if [ "$EDITOR" == "" ]; then
    echo "Set \$EDITOR to open a config file"
    exit 1
fi

edit() {
    eval $EDITOR $1
    echo -e "\x1b[34mDon't forget to apply your changes to the dotfiles\x1b[0m"
}

sudoedit() {
    e=$EDITOR
    eval sudo $e $1
    echo -e "\x1b[34mDon't forget to apply your changes to the dotfiles\x1b[0m"
}

case $1 in
    xinit) edit ~/.xinitrc;;
    xresources|xres) edit ~/.Xresources;;
    xterm) edit ~/.Xresources.d/xterm;;
    sxhkd) edit ~/.config/sxhkd/sxhkdrc;;
    bspwm) edit ~/.config/bspwm/bspwmrc;;
    hosts) sudoedit /etc/hosts;;
    *) echo "No registered config key"; exit 1;;
esac
