#!/bin/bash

box="     "
names=(blk red grn ylw blu mag cyn wht)

echo
for i in {0..7}; do
    echo -en "\033[0;3${i}m ${names[$i]} \033[0m"
done
echo
for i in {0..7}; do
    echo -en "\033[0;4${i}m${box}\033[0m"
done
echo
echo

